# Neural Network from Scratch

### Key Points:

Stage 1:
* 2-layer neural network
* Feedforward with backpropogation
* Framework: Numpy
* Training data: XOR gate operation
* Loss function: Square Root Error
* Activation Function: Sigmoid
* Nodes in first layer = number of inputs
* Nodes in second layer (Hidden layer) = 4

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1.0 - x)

### The NEURAL NETWORK CLASS

In [4]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

### Training Process

In [9]:
if __name__ == "__main__":
    X = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(1500):
        nn.feedforward()
        nn.backprop()

    print(nn.output)

[[0.03861796]
 [0.96425342]
 [0.96514691]
 [0.03352662]]


In [11]:
np.random.rand(2,4)

array([[0.04450026, 0.21171932, 0.107732  , 0.01997913],
       [0.95855404, 0.07461342, 0.90838016, 0.56514638]])

In [13]:
np.array(X)

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [12]:
np.dot(X, np.random.rand(2,4))

array([[0.        , 0.        , 0.        , 0.        ],
       [0.83052098, 0.33650564, 0.16471153, 0.53846382],
       [0.30883732, 0.34643444, 0.40295388, 0.6346386 ],
       [1.1393583 , 0.68294009, 0.56766541, 1.17310242]])

In [14]:
sigmoid(np.dot(X, np.random.rand(2,4)))

array([[0.5       , 0.5       , 0.5       , 0.5       ],
       [0.63827102, 0.50180347, 0.61105724, 0.51173972],
       [0.72251609, 0.72725539, 0.57740456, 0.62475636],
       [0.82125075, 0.72868396, 0.68219689, 0.63570109]])

In [15]:
nn.layer1.T

array([[0.5       , 0.99850478, 0.04275251, 0.96755895],
       [0.5       , 0.99557225, 0.99527655, 0.99997889],
       [0.5       , 0.04590558, 0.99821777, 0.96421991],
       [0.5       , 0.32933937, 0.4521477 , 0.28839922]])